# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\rpythonservice\"\x9f\x01\n\rScriptRequest\x12\x13\n\x0bscript_name\x18\x01 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x02 \x03(\t\x12;\n\x08\x65nv_vars\x18\x03 \x03(\x0b\x32).pythonservice.ScriptRequest.EnvVarsEntry\x1a.\n\x0c\x45nvVarsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"T\n\x0eScriptResponse\x12\x11\n\texit_code\x18\x01 \x01(\x05\x12\x0e\n\x06stdout\x18\x02 \x01(\t\x12\x0e\n\x06stderr\x18\x03 \x01(\t\x12\x0f\n\x07success\x18\x04 \x01(\x08\x32\xb2\x01\n\x0cPythonRunner\x12L\n\rExecuteScript\x12\x1c.pythonservice.ScriptRequest\x1a\x1d.pythonservice.ScriptResponse\x12T\n\x13\x45xecuteScriptStream\x12\x1c.pythonservice.ScriptRequest\x1a\x1d.pythonservice.ScriptResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCRIPTREQUEST_ENVVARSENTRY']._loaded_options = None
  _globals['_SCRIPTREQUEST_ENVVARSENTRY']._serialized_options = b'8\001'
  _globals['_SCRIPTREQUEST']._serialized_start=33
  _globals['_SCRIPTREQUEST']._serialized_end=192
  _globals['_SCRIPTREQUEST_ENVVARSENTRY']._serialized_start=146
  _globals['_SCRIPTREQUEST_ENVVARSENTRY']._serialized_end=192
  _globals['_SCRIPTRESPONSE']._serialized_start=194
  _globals['_SCRIPTRESPONSE']._serialized_end=278
  _globals['_PYTHONRUNNER']._serialized_start=281
  _globals['_PYTHONRUNNER']._serialized_end=459
# @@protoc_insertion_point(module_scope)
